IncomeExpenseAccountt/IncomeExpenseAccountt/Controllers/CategoryTypeController.cs
using IncomeExpenseAccount.Business.Concrete;
using IncomeExpenseAccountt.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IncomeExpenseAccountt.Controllers
{
    public class CategoryTypeController : Controller
    {
        CategoryTypeManager _categoryTypeManager = new CategoryTypeManager();
        // GET: 
        [HttpGet]
        public ActionResult ListCategoryType()
        {
            //var categoryList = _categoryTypeManager.GetAll(null);
            var categoryList = _categoryTypeManager.GetAll();
            return View(categoryList);
        }

        //get ile ben sayfa istiyorum
        [HttpGet]
        public ActionResult AddCategoryType(int id=0)
        {
            CategoryTypeAddViewModel model = new CategoryTypeAddViewModel();

            if (id != 0)
            {
                var categoryType = new CategoryTypeManager().Get(x => x.CategoryTypeId == id);
                model.CategoryType = categoryType;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult AddCategoryType(CategoryTypeAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (model.CategoryType.CategoryTypeId != 0)
                    {
                        //var user = _context.Users.FirstOrDefault(u => u.UserId == model.User.UserId);
                        var categoryType = new CategoryTypeManager().Get(c=> c.CategoryTypeId == model.CategoryType.CategoryTypeId);
                        categoryType.CategoryTypeId = model.CategoryType.CategoryTypeId;
                        categoryType.CategoryTypeName = model.CategoryType.CategoryTypeName;
                        categoryType.CategoryTypeDescription = model.CategoryType.CategoryTypeDescription;
                        new CategoryTypeManager().Update(categoryType);
                    }

                    else
                    {
                        new CategoryTypeManager().Add(model.CategoryType);
                        //_context.Users.Add(model.User);
                    }

                    return RedirectToAction("List");
                }
                catch (Exception exception)
                {
                    ViewBag.Message = exception.Message;
                    return View();
                }
            }
            else
            {
                ViewBag.Message = "Model yanlış";
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteCategoryType(int id)
        {
            var categoryType = new CategoryTypeManager().Get(c=>c.CategoryTypeId == id);
            new CategoryTypeManager().Delete(categoryType);
            return RedirectToAction("List");
        }

        public ActionResult CategoryTypeDetails(int id)
        {
            var model = _categoryTypeManager.Get(x => x.CategoryTypeId == id);
            return View(model);
        }
    }
 }

IncomeExpenseAccountt/IncomeExpenseAccountt/Views/CategoryType/AddCategoryType.cshtml
@model CategoryTypeAddViewModel
@{
    ViewBag.Title = "Yeni Kategori Tipi";
}

<h2>Yeni Kategori Tipi</h2>

@using (Html.BeginForm("AddCategoryType", "CategoryType", FormMethod.Post, new { id = "form" }))
{
    <input name="CategoryType.CategoryTypeId" value="@Model.CategoryType.CategoryTypeId" hidden />
    <div class="form-group">
        <input class="form-control" name="CategoryType.CategoryName" value="@Model.CategoryType.CategoryTypeName" placeholder="Kategori Adını giriniz.." />
    </div>
    <div class="form-group">
        <input class="form-control" name="CategoryType.CategoryTypeDescription" value="@Model.CategoryType.CategoryTypeDescription" placeholder="Kategori Açıklamasını giriniz.." />
    </div>
    <div class="form-group">
        <input id="btnKaydet" class="btn btn-success" type="submit" value="Kaydet" />
    </div>

    @Html.ActionLink("Listeye geri dön", "ListCategoryType", "CategoryType")
}

IncomeExpenseAccountt/IncomeExpenseAccountt/Views/CategoryType/CategoryTypeDetails.cshtml
@model CategoryType
@{
    ViewBag.Title = "Kategori Tip Detayı";
}

<h2>Kategori Tip Detayı</h2>

<div class="form-group" hidden>
    @Html.DisplayNameFor(m=> m.CategoryTypeId)
    <br />
    @Html.DisplayFor(m=> m.CategoryTypeId)
</div>

<div class="form-group">
    @Html.DisplayNameFor(m => m.CategoryTypeName)
    <br />
    @Html.DisplayFor(m => m.CategoryTypeName)
</div>

<div class="form-group">
    @Html.DisplayNameFor(m => m.CategoryTypeDescription)
    <br />
    @Html.DisplayFor(m => m.CategoryTypeDescription)
</div>

@Html.ActionLink("Listeye geri dön","ListCategoryType","CategoryType")

IncomeExpenseAccountt/IncomeExpenseAccountt/Views/CategoryType/ListCategoryType.cshtml
@model  IEnumerable<CategoryType>
@{
    ViewBag.Title = "Kategori Tip Lisetesi";
}

<h2>Kategori Tip Lisetesi</h2>

<p>
    @Html.ActionLink("Yeni", "AddCategoryType", "CategoryType")
</p>
<table class="table">
    <tr>
        <th style="display:none">
            @Html.DisplayNameFor(model => model.CategoryTypeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryTypeDescription)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="display:none">
                @Html.DisplayFor(modelItem => item.CategoryTypeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryTypeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryTypeDescription)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "AddCategoryType", new { id=item.CategoryTypeId }) |
                @Html.ActionLink("Detay", "CategoryTypeDetails", new { id= item.CategoryTypeId }) |
                @Html.ActionLink("Sil", "DeleteCategoryType", new { id=item.CategoryTypeId})
            </td>
        </tr>
    }

</table>